# Generated by Django 5.1.7 on 2025-04-24 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Central',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('foto_central', models.FileField(blank=True, null=True, upload_to='centrales')),
                ('empresa', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=200)),
                ('potencia', models.FloatField()),
                ('e_media', models.FloatField()),
                ('provincia', models.CharField(max_length=200)),
                ('canton', models.CharField(max_length=200)),
                ('anio_operacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoElectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('foto_tipo', models.FileField(blank=True, null=True, upload_to='tipo_electrica')),
            ],
        ),
        migrations.CreateModel(
            name='CentralFotovoltaica',
            fields=[
                ('central_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculo.central')),
                ('costos_produccion', models.FloatField()),
                ('costos_om', models.FloatField()),
                ('costos_variable', models.FloatField()),
            ],
            bases=('calculo.central',),
        ),
        migrations.CreateModel(
            name='CentralTermica',
            fields=[
                ('central_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculo.central')),
                ('costos_produccion', models.FloatField()),
                ('costos_om', models.FloatField()),
                ('costos_administracion', models.FloatField()),
                ('costos_combustible', models.FloatField()),
                ('costos_transporte', models.FloatField()),
                ('costos_lubricacion', models.FloatField()),
                ('costo_agua', models.FloatField()),
                ('costo_mantenimeinto', models.FloatField()),
                ('costo_control_ambiental', models.FloatField()),
                ('costo_servicios_auxiliares', models.FloatField()),
            ],
            bases=('calculo.central',),
        ),
        migrations.CreateModel(
            name='InformacionCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.FloatField()),
                ('vida_util', models.IntegerField()),
                ('inversion', models.FloatField()),
                ('factor_planta', models.FloatField()),
                ('anio', models.CharField(max_length=200)),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informaciones', to='calculo.central')),
            ],
        ),
        migrations.AddField(
            model_name='central',
            name='tipo_electrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centrales', to='calculo.tipoelectrica'),
        ),
    ]
