# Generated by Django 5.1.7 on 2025-04-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoelectrica',
            name='foto_tipo',
            field=models.FileField(blank=True, null=True, upload_to='tipo_electrica'),
        ),
    ]
