# Generated by Django 5.1.7 on 2025-07-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termica',
            name='gal_anio_1',
            field=models.DecimalField(decimal_places=4, help_text='GAL/a', max_digits=20),
        ),
        migrations.AlterField(
            model_name='termica',
            name='gastos_administracion',
            field=models.DecimalField(decimal_places=4, help_text='USD', max_digits=20),
        ),
    ]
