# Generated by Django 5.1.7 on 2025-04-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Central',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('empresa', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=200)),
                ('potencia', models.FloatField()),
                ('e_media', models.FloatField()),
                ('provincia', models.CharField(max_length=200)),
                ('canton', models.CharField(max_length=200)),
                ('anio_operacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoElectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InformacionCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.FloatField()),
                ('vida_util', models.IntegerField()),
                ('inversion', models.FloatField()),
                ('factor_planta', models.FloatField()),
                ('anio', models.CharField(max_length=200)),
                ('central', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informaciones', to='calculo.central')),
            ],
        ),
        migrations.AddField(
            model_name='central',
            name='tipo_electrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centrales', to='calculo.tipoelectrica'),
        ),
    ]
