# Generated by Django 5.1.7 on 2025-06-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central',
            name='anio_operacion',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='anio_ingreso',
            field=models.CharField(),
        ),
    ]
