# Generated by Django 5.1.7 on 2025-04-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centralfotovoltaica',
            old_name='costos_produccion',
            new_name='costos_prod',
        ),
        migrations.RenameField(
            model_name='centralfotovoltaica',
            old_name='costos_variable',
            new_name='costos_var',
        ),
    ]
