# Generated by Django 5.1.7 on 2025-06-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotovoltaica',
            name='capital_propio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='deuda',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
