# Generated by Django 5.1.7 on 2025-07-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0002_alter_termica_gal_anio_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotovoltaica',
            name='inversion_total',
            field=models.DecimalField(decimal_places=4, help_text='USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='agua',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='combustible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='control',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='costo_fijo_anual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='costo_fijo_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='costo_fijo_mw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='costo_inversion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='lubricantes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='mantenimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='personal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='seguros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='servicios',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametroeolica',
            name='transporte',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
