# Generated by Django 5.1.7 on 2025-05-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0002_rename_costos_produccion_centralfotovoltaica_costos_prod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centraltermica',
            old_name='costo_mantenimeinto',
            new_name='costo_mantenimiento',
        ),
    ]
