# Generated by Django 5.1.7 on 2025-04-15 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0002_central_tipoelectrica_informacioncentral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralTermica',
            fields=[
                ('central_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculo.central')),
                ('inversion_total', models.FloatField()),
                ('factor_planta', models.FloatField()),
                ('costos_produccion', models.FloatField()),
                ('costos_om', models.FloatField()),
                ('costos_variable', models.FloatField()),
            ],
            bases=('calculo.central',),
        ),
    ]
