# Generated by Django 5.1.7 on 2025-06-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0002_alter_fotovoltaica_capital_propio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrocalculo',
            name='potencia_nominal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
