# Generated by Django 5.1.7 on 2025-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0002_tipoelectrica_foto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='central',
            name='foto_central',
            field=models.FileField(blank=True, null=True, upload_to='centrales'),
        ),
    ]
