# Generated by Django 5.1.7 on 2025-06-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0003_parametrocalculo_potencia_nominal'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadocalculo',
            name='detalle',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
