# Generated by Django 5.1.7 on 2025-05-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0003_rename_costo_mantenimeinto_centraltermica_costo_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotovoltaica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_ingreso', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('numero_paneles', models.IntegerField()),
                ('sistema', models.CharField(max_length=100)),
                ('potencia_nominal_mw', models.FloatField()),
                ('potencia_efectiva_mwp', models.FloatField()),
                ('energia_bruta_gwh', models.FloatField()),
                ('energia_anual_producida_mwh', models.FloatField()),
                ('factor_planta', models.FloatField()),
                ('vida_util', models.FloatField()),
                ('degradacion', models.FloatField()),
                ('inversion_total_usd', models.FloatField()),
                ('capital_propio_porcentaje', models.FloatField()),
                ('capital_propio_usd', models.FloatField()),
                ('acreedor', models.CharField(max_length=255)),
                ('deuda_porcentaje', models.FloatField()),
                ('deuda_usd', models.FloatField()),
                ('tasa_interes_anual', models.FloatField()),
                ('tasa_interes_periodo', models.FloatField()),
                ('periodos_por_anio', models.IntegerField()),
                ('anios_pago_total', models.IntegerField()),
                ('total_periodos', models.IntegerField()),
                ('anios_gracia', models.IntegerField()),
                ('periodos_gracia', models.IntegerField()),
                ('periodos_pago', models.IntegerField()),
                ('anios_pago', models.FloatField()),
                ('costo_variables', models.IntegerField()),
                ('costo_produccion_usd', models.FloatField()),
                ('costo_anual_oma_usd', models.FloatField()),
                ('costo_anual_oma_inversion', models.FloatField()),
                ('costo_anual_oma_mw', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='centraltermica',
            name='central_ptr',
        ),
        migrations.DeleteModel(
            name='CentralFotovoltaica',
        ),
        migrations.DeleteModel(
            name='CentralTermica',
        ),
    ]
