# Generated by Django 5.1.7 on 2025-07-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0003_parametrotermica_termica_delete_parametrogenerico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrofotovoltaica',
            name='costo_operacion_anual',
        ),
        migrations.RemoveField(
            model_name='parametrotermica',
            name='costo_operacion_anual',
        ),
    ]
