# Generated by Django 5.1.7 on 2025-06-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0004_resultadocalculo_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadocalculo',
            name='lcoe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
