# Generated by Django 5.1.7 on 2025-05-19 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0004_fotovoltaica_remove_centraltermica_central_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fotovoltaica',
        ),
    ]
