# Generated by Django 5.1.7 on 2025-06-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0005_alter_resultadocalculo_lcoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrocalculo',
            name='degradacion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
