# Generated by Django 5.1.7 on 2025-05-19 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0005_delete_fotovoltaica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotovoltaica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_ingreso', models.PositiveIntegerField()),
                ('numero_paneles', models.IntegerField()),
                ('sistema', models.CharField(max_length=100)),
                ('potencia_nominal', models.FloatField(help_text='MW')),
                ('potencia_efectiva', models.FloatField(help_text='MWp')),
                ('energia_bruta', models.FloatField(help_text='GWh')),
                ('energia_anual_producida', models.FloatField(help_text='MWh/año')),
                ('energia_bruta_calculada', models.FloatField(blank=True, editable=False, null=True)),
                ('factor_planta', models.FloatField(help_text='%')),
                ('vida_util', models.FloatField(help_text='%')),
                ('degradacion', models.FloatField(help_text='%')),
                ('inversion_total', models.FloatField(help_text='USD')),
                ('capital_propio', models.FloatField(help_text='USD')),
                ('acreedor', models.CharField(max_length=100)),
                ('deuda', models.FloatField(help_text='USD')),
                ('tasa_interes_anual', models.FloatField(help_text='%')),
                ('tasa_interes_periodo', models.FloatField(help_text='%')),
                ('periodos_por_anio', models.IntegerField()),
                ('anios_pago_total', models.IntegerField()),
                ('total_periodos', models.IntegerField()),
                ('anios_gracia', models.IntegerField()),
                ('periodos_gracia', models.IntegerField()),
                ('periodos_pago', models.IntegerField()),
                ('anios_pago', models.IntegerField()),
                ('costo_variable', models.FloatField(help_text='USD')),
                ('costo_produccion', models.FloatField(help_text='USD')),
                ('costo_anual_oma', models.FloatField(help_text='USD')),
                ('costo_anual_oma_inversion', models.FloatField(help_text='%')),
                ('costo_anual_oma_mw', models.FloatField(help_text='USD/MW-año')),
                ('central', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fotovoltaica', to='calculo.central')),
            ],
        ),
    ]
