# Generated by Django 5.1.7 on 2025-06-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0006_parametrocalculo_degradacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotovoltaica',
            name='vida_util',
            field=models.IntegerField(help_text='%'),
        ),
    ]
