# Generated by Django 5.1.7 on 2025-05-20 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0006_fotovoltaica'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('es_simulacion', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('central', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculo.central')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inversion_total', models.FloatField()),
                ('energia_anual_producida', models.FloatField()),
                ('vida_util', models.FloatField()),
                ('tasa_descuento', models.FloatField()),
                ('tasa_crecimiento_energia', models.FloatField(default=0.0)),
                ('costo_operacion_anual', models.FloatField()),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculo.casocalculo')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcoe', models.FloatField()),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculo.casocalculo')),
            ],
        ),
    ]
