# Generated by Django 5.1.7 on 2025-06-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0007_alter_fotovoltaica_vida_util'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central',
            name='anio_operacion',
            field=models.PositiveIntegerField(),
        ),
    ]
