# Generated by Django 5.1.7 on 2025-05-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0007_casocalculo_parametrocalculo_resultadocalculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotovoltaica',
            name='energia_bruta',
        ),
    ]
