# Generated by Django 5.1.7 on 2025-06-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0008_alter_central_anio_operacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrocalculo',
            name='vida_util',
            field=models.IntegerField(),
        ),
    ]
