# Generated by Django 5.1.7 on 2025-06-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0009_alter_parametrocalculo_vida_util'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadocalculo',
            name='detalle',
        ),
    ]
