# Generated by Django 5.1.7 on 2025-06-18 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0010_remove_resultadocalculo_detalle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParametroCalculo',
            new_name='ParametroFotovoltaica',
        ),
        migrations.CreateModel(
            name='ParametroGenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_generacion', models.CharField(blank=True, max_length=100, null=True)),
                ('inversion_total', models.FloatField()),
                ('energia_anual_producida', models.FloatField()),
                ('vida_util', models.IntegerField()),
                ('tasa_descuento', models.FloatField()),
                ('tasa_crecimiento_energia', models.FloatField(default=0.0)),
                ('costo_operacion_anual', models.FloatField()),
                ('capital_propio', models.FloatField(blank=True, null=True)),
                ('deuda', models.FloatField(blank=True, null=True)),
                ('porcentaje_capital_propio', models.FloatField(blank=True, null=True)),
                ('porcentaje_deuda', models.FloatField(blank=True, null=True)),
                ('degradacion', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('impuesto', models.FloatField(blank=True, null=True)),
                ('margen_intermediacion', models.FloatField(blank=True, null=True)),
                ('inflacion', models.FloatField(blank=True, null=True)),
                ('economia', models.FloatField(blank=True, null=True)),
                ('riesgo', models.FloatField(blank=True, null=True)),
                ('indice_premio', models.FloatField(blank=True, null=True)),
                ('sin_riesgo', models.FloatField(blank=True, null=True)),
                ('tasa_mercado', models.FloatField(blank=True, null=True)),
                ('premio_riesgo_mercado', models.FloatField(blank=True, null=True)),
                ('factor_planta', models.FloatField(blank=True, null=True)),
                ('potencia_nominal', models.FloatField(blank=True, null=True)),
                ('tasa_interes_periodo', models.FloatField(blank=True, null=True)),
                ('tasa_interes_anual', models.FloatField(blank=True, null=True)),
                ('total_periodos', models.IntegerField(blank=True, null=True)),
                ('anios_gracia', models.IntegerField(blank=True, null=True)),
                ('periodos_pago', models.IntegerField(blank=True, null=True)),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculo.casocalculo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
