# Generated by Django 5.1.7 on 2025-06-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo', '0011_rename_parametrocalculo_parametrofotovoltaica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central',
            name='potencia',
            field=models.DecimalField(decimal_places=6, help_text='MW', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='anios_pago',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='beta',
            field=models.DecimalField(decimal_places=4, help_text='Coeficiente beta', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='capital_propio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='costo_anual_oma',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='costo_anual_oma_inversion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='costo_anual_oma_mw',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='costo_produccion',
            field=models.DecimalField(decimal_places=6, help_text='USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='costo_variable',
            field=models.DecimalField(decimal_places=6, help_text='USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='degradacion',
            field=models.DecimalField(decimal_places=4, help_text='%', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='deuda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='economia',
            field=models.DecimalField(decimal_places=4, help_text='%', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='energia_anual_producida',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='MWh/año', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='energia_bruta_calculada',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='factor_planta',
            field=models.DecimalField(decimal_places=4, help_text='%', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='impuesto',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='% impuesto', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='indice_premio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='inflacion',
            field=models.DecimalField(decimal_places=4, help_text='%', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='inversion_total',
            field=models.DecimalField(decimal_places=2, help_text='USD', max_digits=20),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='margen_intermediacion',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='%', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='porcentaje_capital_propio',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='%', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='porcentaje_deuda',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='%', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='potencia_efectiva',
            field=models.DecimalField(decimal_places=6, help_text='MWp', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='potencia_nominal',
            field=models.DecimalField(decimal_places=6, help_text='MW', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='premio_riesgo_mercado',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='% premio riesgo mercado', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='riesgo',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Riesgo país', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='sin_riesgo',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='% tasa sin riesgo', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='tasa_interes_anual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='tasa_interes_periodo',
            field=models.DecimalField(decimal_places=4, help_text='%', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='tasa_mercado',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='% tasa mercado', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fotovoltaica',
            name='vida_util',
            field=models.IntegerField(help_text='años'),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='capital_propio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='costo_anual_oma_mw',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='costo_operacion_anual',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='costo_produccion',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='costo_variable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='degradacion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='deuda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='economia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='energia_anual_producida',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='factor_planta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='impuesto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='indice_premio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='inflacion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='inversion_total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='margen_intermediacion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='porcentaje_capital_propio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='porcentaje_deuda',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='potencia_nominal',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='premio_riesgo_mercado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='riesgo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='sin_riesgo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='tasa_crecimiento_energia',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='tasa_descuento',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='tasa_interes_anual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='tasa_interes_periodo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrofotovoltaica',
            name='tasa_mercado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='beta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='capital_propio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='costo_operacion_anual',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='degradacion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='deuda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='economia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='energia_anual_producida',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='factor_planta',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='impuesto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='indice_premio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='inflacion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='inversion_total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='margen_intermediacion',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='porcentaje_capital_propio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='porcentaje_deuda',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='potencia_nominal',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='premio_riesgo_mercado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='riesgo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='sin_riesgo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='tasa_crecimiento_energia',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='tasa_descuento',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='tasa_interes_anual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='tasa_interes_periodo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametrogenerico',
            name='tasa_mercado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultadocalculo',
            name='lcoe',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
    ]
